FROM apache/airflow:latest

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
       build-essential python3-dev libgomp1 \
  && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt && \
    python -c "import mlflow; print('MLflow installed successfully:', mlflow.__version__)"
