FROM apache/airflow:3.1.0

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential python3-dev \
 && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt .
# COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r requirements-airflow.txt
